/**
 * A symbol table that stores information about each token that is generated by the lexical analyser using an internal
 * one-to-one hash table.
 *
 * @author Michael Connor
 */
public class SymbolTable {
}
